# Generated by Django 4.2.13 on 2024-07-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minibar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
