# Generated by Django 4.2.13 on 2024-07-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minibar", "0003_alter_sale_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateField(),
        ),
    ]
